### ISSUE TITLE
关于人脸识别实验

### ISSUE THREAD

**Issue by Stalker-DAs** [echoanran/On-Mitigating-Hard-Clusters#1]
您好。请问您在5.4 Face Recognition实验中使用的人脸识别模型是什么？如果方便的话可以开源或给个链接吗？

**Comment by chen-yingjie** [comment]
人脸识别实验里我们用的是Resnet50 + Arcface loss

**Comment by Stalker-DAs** [comment]
好的，十分感谢您的回复。
