### ISSUE TITLE
How to divide dataset according to cluster size or sparsity?

### ISSUE THREAD

**Issue by kdh4672** [echoanran/On-Mitigating-Hard-Clusters#2]
Table 2 & Table 3 shows you divide the datasets into 5

May I know the criterion for it? 

ex) sz-1 's cluster size is upper than 120,    80 < sz-2's cluster size < 120

**Comment by chen-yingjie** [comment]
Sorry for the late reply. We first sort all clusters by size or sparsity and divide the dataset uniformly into 5 bins according to the number of clusters, each of which contains 1/5 clusters.

**Comment by kdh4672** [comment]
I got it.
thank you for answer
