### ISSUE TITLE
您好，关于人脸聚类我有个问题想跟您讨论一下。

### ISSUE THREAD

**Issue by VividBinGo** [echoanran/On-Mitigating-Hard-Clusters#3]
在我的认知里，聚类任务通常是无监督方法的，但在阅读近两年的人脸聚类任务后我发现大部分人脸聚类都是监督方法，这样人脸聚类任务和人脸识别任务有什么区别？

**Comment by chen-yingjie** [comment]
对于人脸聚类任务，train和eval的样本identity是不重叠的，eval的样本是从未见过的
